import type { Tender } from "./types";

// Faz 7 (FastAPI) bağlanana kadar dashboard'u çalışır tutmak için gerçekçi
// mock veri. Alan yapısı api/schemas.py::TenderOut ile birebir aynı.

export const mockTenders: Tender[] = [
  {
    id: 1,
    source: "istanbul",
    external_id: "2026/145892",
    ikn: "2026/145892",
    title: "Kurumsal Yazılım Lisans Yenileme Alımı",
    tender_type: "mal_alimi",
    procedure: "Açık İhale Usulü",
    tender_datetime: "2026-08-24T10:00:00",
    unit: "Bilgi İşlem Daire Başkanlığı",
    status: null,
    description: "Kurum genelinde kullanılan yazılım lisanslarının yenilenmesi işi.",
    delivery_place: "İstanbul Büyükşehir Belediyesi Bilgi İşlem Daire Başkanlığı",
    duration: "30 gün",
    venue: "İBB Bakırköy Ek Hizmet Binası İhale Salonu",
    address: "Osmaniye Mah. Çobançeşme Koşuyolu Bulvarı No:5 Bakırköy/İstanbul",
    phone: "0212 449 40 64",
    detail_url: "https://ibb.istanbul/ibb/ihaleler/ihale-ilanlari/kurumsal-yazilim-lisans-2026-145892",
    doc_url: null,
    province: "İstanbul",
    institution: "İstanbul Büyükşehir Belediyesi",
    raw_data: {},
    first_seen_at: "2026-07-10T09:15:00+03:00",
    last_seen_at: "2026-07-16T09:15:00+03:00",
  },
  {
    id: 2,
    source: "ankara",
    external_id: "2026/882216",
    ikn: "2026/882216",
    title: "Ankara İli, Altındağ İlçesi, Konya Sokak Sağlıklaştırma Yapım İşi",
    tender_type: "yapim_isi",
    procedure: "Açık İhale Usulü",
    tender_datetime: "2026-08-02T10:00:00",
    unit: "Kent Tarihi, Tanıtım ve Turizm Dairesi Başkanlığı",
    status: null,
    description: "189 Pozdan oluşan sokak sağlıklaştırma yapım işi.",
    delivery_place: null,
    duration: null,
    venue: "Hipodrom Caddesi No:5 7. Kat İhale Toplantı Salonu Yenimahalle/Ankara",
    address: "Emniyet Mah. Hipodrom Caddesi No:5 Yenimahalle/Ankara",
    phone: "0312 507 40 01",
    detail_url: "https://www.ankara.bel.tr/ihaleler/detay/4065",
    doc_url: null,
    province: "Ankara",
    institution: "Ankara Büyükşehir Belediyesi",
    raw_data: {},
    first_seen_at: "2026-06-20T14:02:00+03:00",
    last_seen_at: "2026-07-16T09:15:00+03:00",
  },
  {
    id: 3,
    source: "kocaeli",
    external_id: "2026/1262113",
    ikn: "2026/1262113",
    title: "Mobil İletişim ve Koordinasyon Aracı Alımı",
    tender_type: "mal_alimi",
    procedure: "Açık İhale Usulü",
    tender_datetime: "2026-08-13T11:00:00",
    unit: "Afet İşleri ve Risk Yönetimi Dairesi Başkanlığı",
    status: null,
    description: "1 adet Kamyon, 1 adet kamyonet Mobil İletişim ve Koordinasyon Aracı",
    delivery_place: "Afet İşleri ve Risk Yönetimi Dairesi Başkanlığı",
    duration: "120 gün",
    venue: "Kocaeli Büyükşehir Belediyesi İhale Toplantı Salonu B Blok 1. Kat İzmit/Kocaeli",
    address: "Kozluk Mah. Sümer Sok. No:8 İzmit/Kocaeli",
    phone: "0262 310 81 17",
    detail_url: "https://www.kocaeli.bel.tr/haber/mobil-iletisim-ve-koordinasyon-araci-alimi-51555.html",
    doc_url: null,
    province: "Kocaeli",
    institution: "Kocaeli Büyükşehir Belediyesi",
    raw_data: {},
    first_seen_at: "2026-07-14T09:41:00+03:00",
    last_seen_at: "2026-07-16T09:15:00+03:00",
  },
  {
    id: 4,
    source: "istanbul",
    external_id: "2026/156999",
    ikn: "2026/156999",
    title: "Bulut Yedekleme Hizmeti Alımı",
    tender_type: "hizmet_alimi",
    procedure: "Açık İhale Usulü",
    tender_datetime: "2026-09-01T10:30:00",
    unit: "Bilgi İşlem Daire Başkanlığı",
    status: null,
    description: "Kurumsal verilerin bulut ortamında yedeklenmesi hizmeti.",
    delivery_place: null,
    duration: "365 gün",
    venue: "İBB Bakırköy Ek Hizmet Binası İhale Salonu",
    address: "Osmaniye Mah. Çobançeşme Koşuyolu Bulvarı No:5 Bakırköy/İstanbul",
    phone: "0212 449 40 64",
    detail_url: "https://ibb.istanbul/ibb/ihaleler/ihale-ilanlari/bulut-yedekleme-2026-156999",
    doc_url: null,
    province: "İstanbul",
    institution: "İstanbul Büyükşehir Belediyesi",
    raw_data: {},
    first_seen_at: "2026-07-01T11:00:00+03:00",
    last_seen_at: "2026-07-16T09:15:00+03:00",
  },
  {
    id: 5,
    source: "ankara",
    external_id: "2026/958278",
    ikn: "2026/958278",
    title: "Bala İlçesi, Beynam Mahallesi İmar Planına Esas Jeoloji/Jeoteknik Etüt Yapımı Hizmet Alımı",
    tender_type: "hizmet_alimi",
    procedure: "Açık İhale Usulü",
    tender_datetime: "2026-08-02T10:00:00",
    unit: "İmar ve Şehircilik Dairesi Başkanlığı",
    status: null,
    description: "630 metre sondajlı jeolojik/jeoteknik etüt yapımı.",
    delivery_place: "Ankara",
    duration: null,
    venue: "Emniyet Mah. Hipodrom Cad. No:5 B Blok Kat:7 Yenimahalle/Ankara",
    address: "Emniyet Mah. Hipodrom Cad. No:5 Yenimahalle/Ankara",
    phone: "0312 507 30 01",
    detail_url: "https://www.ankara.bel.tr/ihaleler/detay/4075",
    doc_url: null,
    province: "Ankara",
    institution: "Ankara Büyükşehir Belediyesi",
    raw_data: {},
    first_seen_at: "2026-06-18T10:00:00+03:00",
    last_seen_at: "2026-07-16T09:15:00+03:00",
  },
  {
    id: 6,
    source: "istanbul",
    external_id: "2026/606480",
    ikn: "2026/606480",
    title: "195 Kalem Kırtasiye ve Eğitim Malzemesi Alımı",
    tender_type: "mal_alimi",
    procedure: "Açık İhale Usulü",
    tender_datetime: "2026-07-24T10:30:00",
    unit: "Levazım ve Ayniyat Şube Müdürlüğü",
    status: null,
    description: "Kırtasiye ve eğitim malzemesi alımı (195 kalem mal alımı).",
    delivery_place: "İstanbul ili sınırları içerisinde idarenin göstereceği noktalar",
    duration: "45 gün",
    venue: "İBB Bakırköy Ek Hizmet Binası İhale Salonu",
    address: "Osmaniye Mah. Çobançeşme Koşuyolu Bulvarı No:5 Bakırköy/İstanbul",
    phone: "0212 449 40 64",
    detail_url: "https://ibb.istanbul/ibb/ihaleler/ihale-ilanlari/kirtasiye-2026-606480",
    doc_url: null,
    province: "İstanbul",
    institution: "İstanbul Büyükşehir Belediyesi",
    raw_data: {},
    first_seen_at: "2026-05-02T08:35:00+03:00",
    last_seen_at: "2026-07-16T09:15:00+03:00",
  },
  {
    id: 7,
    source: "kocaeli",
    external_id: "2026/1244086",
    ikn: "2026/1244086",
    title: "Portatif Küçükbaş Hayvan Çadırı ve Mantar Üretim Çadırı Alımı (Montaj Dahil)",
    tender_type: "mal_alimi",
    procedure: "Açık İhale Usulü",
    tender_datetime: "2026-07-29T11:00:00",
    unit: "Tarımsal Hizmetler Şube Müdürlüğü",
    status: null,
    description: "Muhtarlık İşleri Dairesi Başkanlığı bünyesinde dağıtılacak çadırların alımı.",
    delivery_place: "Kocaeli",
    duration: "60 gün",
    venue: "Kocaeli Büyükşehir Belediyesi İhale Toplantı Salonu",
    address: "İzmit/Kocaeli",
    phone: "0262 318 20 00",
    detail_url: "https://www.kocaeli.bel.tr/haber/portatif-kucukbas-hayvan-cadiri-51554.html",
    doc_url: null,
    province: "Kocaeli",
    institution: "Kocaeli Büyükşehir Belediyesi",
    raw_data: {},
    first_seen_at: "2026-07-14T09:30:00+03:00",
    last_seen_at: "2026-07-16T09:15:00+03:00",
  },
  {
    id: 8,
    source: "istanbul",
    external_id: "2026/arsa-fatih-balat",
    ikn: null,
    title: "Arsa Satışı, Fatih, Balat Karabaş/Çınçınlı Çeşme",
    tender_type: "tasinmaz_satis",
    procedure: "Açık Teklif Usulü",
    tender_datetime: "2026-07-23T14:00:00",
    unit: "Emlak Müdürlüğü",
    status: null,
    description: "Mülkiyeti İBB'ye ait taşınmazın satışı.",
    delivery_place: null,
    duration: null,
    venue: "İBB Encümen Salonu Saraçhane/Fatih",
    address: "Saraçhane, Fatih/İstanbul",
    phone: "0212 455 33 61",
    detail_url: "https://ibb.istanbul/ibb/ihaleler/ihale-ilanlari/arsa-satisi-fatih-balat",
    doc_url: null,
    province: "İstanbul",
    institution: "İstanbul Büyükşehir Belediyesi",
    raw_data: {},
    first_seen_at: "2026-06-10T09:00:00+03:00",
    last_seen_at: "2026-07-16T09:15:00+03:00",
  },
  {
    id: 9,
    source: "ankara",
    external_id: "ankara-detay-4077",
    ikn: null,
    title: "Taşınmaz Kiralama İhale İlanı (Anafartalar Çarşısı ve Ulus İşyerleri)",
    tender_type: "kiralama",
    procedure: "Açık Teklif Usulü",
    tender_datetime: "2026-07-02T14:00:00",
    unit: "Emlak ve İstimlak Dairesi Başkanlığı",
    status: null,
    description: "Mülkiyeti/tasarrufu belediyeye ait taşınmazların kiraya verilmesi.",
    delivery_place: null,
    duration: "3 yıl",
    venue: "Ankara Büyükşehir Belediyesi Encümen Salonu",
    address: "Emniyet Mah. Hipodrom Caddesi No:5 Kat 13 Yenimahalle/Ankara",
    phone: "0312 507 25 89",
    detail_url: "https://www.ankara.bel.tr/ihaleler/detay/4077",
    doc_url: null,
    province: "Ankara",
    institution: "Ankara Büyükşehir Belediyesi",
    raw_data: {},
    first_seen_at: "2026-06-01T10:00:00+03:00",
    last_seen_at: "2026-07-16T09:15:00+03:00",
  },
  {
    id: 10,
    source: "ankara",
    external_id: "ankara-detay-4078",
    ikn: null,
    title: "Arsa Payı (Kat) Karşılığı İnşaat Yaptırılacaktır",
    tender_type: "kat_karsiligi",
    procedure: "Açık Teklif Usulü",
    tender_datetime: "2026-07-16T14:00:00",
    unit: "Emlak ve İstimlak Dairesi Başkanlığı",
    status: null,
    description: "Mamak İlçesi, Kusunlar Mahallesi imar parseli üzerinde kat karşılığı inşaat işi.",
    delivery_place: null,
    duration: null,
    venue: "Ankara Büyükşehir Belediyesi Hipodrom Caddesi No:5 Kat 1 Yenimahalle/Ankara",
    address: "Emniyet Mahallesi Hipodrom Caddesi No:5 Kat:14 Yenimahalle/Ankara",
    phone: "0312 507 25 63",
    detail_url: "https://www.ankara.bel.tr/ihaleler/detay/4078",
    doc_url: null,
    province: "Ankara",
    institution: "Ankara Büyükşehir Belediyesi",
    raw_data: {},
    first_seen_at: "2026-05-20T10:00:00+03:00",
    last_seen_at: "2026-07-16T09:15:00+03:00",
  },
  {
    id: 11,
    source: "istanbul",
    external_id: "2026/1172633",
    ikn: "2026/1172633",
    title: "Avrupa Yakası İBB Hizmet Binaları Mekanik, Elektrik ve İş Ekipmanları Periyodik Muayeneleri",
    tender_type: "hizmet_alimi",
    procedure: "Açık İhale Usulü",
    tender_datetime: "2026-12-05T14:30:00",
    unit: "Tesisler Bakım ve Onarım Şube Müdürlüğü",
    status: null,
    description: "56 kalemden oluşan periyodik muayene ve ortam ölçümleri hizmeti.",
    delivery_place: "İBB Bakırköy Ek Hizmet Binası",
    duration: "240 gün",
    venue: "İBB Bakırköy Ek Hizmet Binası İhale Salonu",
    address: "Akşemsettin Mah. Akşemsettin Bulvarı No:138 Eyüpsultan/İstanbul",
    phone: "0212 600 88 05",
    detail_url: "https://ibb.istanbul/ibb/ihaleler/ihale-ilanlari/periyodik-muayene-2026-1172633",
    doc_url: null,
    province: "İstanbul",
    institution: "İstanbul Büyükşehir Belediyesi",
    raw_data: {},
    first_seen_at: "2026-06-11T09:29:00+03:00",
    last_seen_at: "2026-07-16T09:15:00+03:00",
  },
  {
    id: 12,
    source: "kocaeli",
    external_id: "2026/1223661",
    ikn: "2026/1223661",
    title: "Körfezray Projesi Hattı Boyunca Görsel Dil Modelleri İle Yüzey Hareketlerinin Tespiti Hizmeti",
    tender_type: "hizmet_alimi",
    procedure: "Açık İhale Usulü",
    tender_datetime: "2026-07-27T11:00:00",
    unit: "Coğrafi Bilgi Sistemleri Şube Müdürlüğü",
    status: null,
    description: "Metro hattı boyunca dijital veri çıktılarının oluşturulması ve raporlanması.",
    delivery_place: null,
    duration: null,
    venue: "Kocaeli Büyükşehir Belediyesi İhale Salonu",
    address: "İzmit/Kocaeli",
    phone: "0262 318 20 00",
    detail_url: "https://www.kocaeli.bel.tr/haber/korfezray-projesi-51534.html",
    doc_url: null,
    province: "Kocaeli",
    institution: "Kocaeli Büyükşehir Belediyesi",
    raw_data: {},
    first_seen_at: "2026-07-10T08:00:00+03:00",
    last_seen_at: "2026-07-16T09:15:00+03:00",
  },
  {
    id: 13,
    source: "istanbul",
    external_id: "2026/yol-koprü-2026",
    ikn: "2026/990112",
    title: "İstanbul Geneli Köy Mezarlıklarında Çevre Düzenleme Yapım İşi",
    tender_type: "yapim_isi",
    procedure: "Açık İhale Usulü",
    tender_datetime: "2026-08-11T10:00:00",
    unit: "Mezarlıklar Destek Hizmetleri Müdürlüğü",
    status: null,
    description: "Köy mezarlıklarında çevre düzenleme ve peyzaj yapım işi.",
    delivery_place: null,
    duration: "180 gün",
    venue: "İBB Bakırköy Ek Hizmet Binası İhale Salonu",
    address: "Esentepe Mah. Büyükdere Cad. No:169 Şişli/İstanbul",
    phone: "0212 312 65 70",
    detail_url: "https://ibb.istanbul/ibb/ihaleler/ihale-ilanlari/koy-mezarliklari-2026",
    doc_url: null,
    province: "İstanbul",
    institution: "İstanbul Büyükşehir Belediyesi",
    raw_data: {},
    first_seen_at: "2026-06-25T10:00:00+03:00",
    last_seen_at: "2026-07-16T09:15:00+03:00",
  },
  {
    id: 14,
    source: "ankara",
    external_id: "2026/1174861",
    ikn: "2026/1174861",
    title: "Beynam Arazi Tipi 50 MW Güneş Enerji Santrali Yapım İşi",
    tender_type: "yapim_isi",
    procedure: "Açık İhale Usulü",
    tender_datetime: "2026-08-03T10:30:00",
    unit: "Etüt ve Projeler Dairesi Başkanlığı",
    status: null,
    description: "50 MW kapasiteli güneş enerji santrali kurulumu.",
    delivery_place: null,
    duration: null,
    venue: "Ankara Büyükşehir Belediyesi İhale Salonu",
    address: "Emniyet Mah. Hipodrom Caddesi No:5 Yenimahalle/Ankara",
    phone: "0312 507 30 01",
    detail_url: "https://www.ankara.bel.tr/ihaleler/detay/4084",
    doc_url: null,
    province: "Ankara",
    institution: "Ankara Büyükşehir Belediyesi",
    raw_data: {},
    first_seen_at: "2026-07-03T10:30:00+03:00",
    last_seen_at: "2026-07-16T09:15:00+03:00",
  },
  {
    id: 15,
    source: "istanbul",
    external_id: "2026/otomat-lokasyon",
    ikn: null,
    title: "Spor Tesisleri ve Stadyumlara Otomat Konularak İşletmeye Verilmesi İşi",
    tender_type: "diger",
    procedure: "Açık Teklif Arttırma Usulü",
    tender_datetime: "2026-03-03T11:00:00",
    unit: "İşletmeler Daire Başkanlığı",
    status: null,
    description: "60 lokasyonda 74 adet otomat 3 yıl süreyle işletmeye verilecek.",
    delivery_place: null,
    duration: "3 yıl",
    venue: "İBB Encümen Salonu Saraçhane-Fatih/İstanbul",
    address: "Saraçhane-Fatih/İstanbul",
    phone: null,
    detail_url: "https://ibb.istanbul/ibb/ihaleler/ihale-ilanlari/otomat-lokasyon",
    doc_url: null,
    province: "İstanbul",
    institution: "İstanbul Büyükşehir Belediyesi",
    raw_data: {},
    first_seen_at: "2026-02-01T09:00:00+03:00",
    last_seen_at: "2026-07-16T09:15:00+03:00",
  },
  {
    id: 16,
    source: "kocaeli",
    external_id: "2026/1289366",
    ikn: "2026/1289366",
    title: "Kışlık İş Elbisesi Satın Alınacaktır",
    tender_type: "mal_alimi",
    procedure: "Açık İhale Usulü",
    tender_datetime: "2026-08-11T11:00:00",
    unit: "Genel Sekreterlik",
    status: null,
    description: "Toplamda 14.067 adet iş elbisesi ve ekipmanları alımı.",
    delivery_place: "Melid Ulaşım ve Hizmet Grupları'nın belirleyeceği adres",
    duration: "45 gün",
    venue: "İnönü Mah. İnönü Cad. No:182 Yeşilyurt/Malatya",
    address: "İnönü Mahallesi İnönü Caddesi No:197/5 Yeşilyurt/Malatya",
    phone: "0531 713 06 07",
    detail_url: "https://www.kocaeli.bel.tr/haber/kislik-is-elbisesi-2026.html",
    doc_url: null,
    province: "Kocaeli",
    institution: "Kocaeli Büyükşehir Belediyesi",
    raw_data: {},
    first_seen_at: "2026-07-01T08:00:00+03:00",
    last_seen_at: "2026-07-16T09:15:00+03:00",
  },
  {
    id: 17,
    source: "istanbul",
    external_id: "2026/kompresor-2026",
    ikn: "2026/774521",
    title: "Kompresör, İnşaat Ekipmanı ve Atölye Malzemeleri Satın Alınacaktır",
    tender_type: "mal_alimi",
    procedure: "Açık İhale Usulü",
    tender_datetime: "2026-07-20T10:00:00",
    unit: "Makine İkmal Bakım ve Onarım Dairesi Başkanlığı",
    status: null,
    description: "Muhtelif kompresör ve atölye ekipmanı alımı.",
    delivery_place: "Makine İkmal Bakım ve Onarım Dairesi Başkanlığı",
    duration: "60 gün",
    venue: "İBB Bakırköy Ek Hizmet Binası İhale Salonu",
    address: "Zübeyde Hanım Mahallesi Etlik Cad. No:21 Altındağ/Ankara",
    phone: "0212 449 40 64",
    detail_url: "https://ibb.istanbul/ibb/ihaleler/ihale-ilanlari/kompresor-2026",
    doc_url: null,
    province: "İstanbul",
    institution: "İstanbul Büyükşehir Belediyesi",
    raw_data: {},
    first_seen_at: "2026-06-05T10:00:00+03:00",
    last_seen_at: "2026-07-16T09:15:00+03:00",
  },
  {
    id: 18,
    source: "ankara",
    external_id: "2026/1208143",
    ikn: "2026/1208143",
    title: "Ankara'nın Muhtelif İlçelerinde 20 Adet Dere Geçiş Yapılarının Yapımı",
    tender_type: "yapim_isi",
    procedure: "Açık İhale Usulü",
    tender_datetime: "2026-07-27T10:30:00",
    unit: "Etüt ve Projeler Dairesi Başkanlığı",
    status: null,
    description: "20 adet dere geçiş yapısının inşası.",
    delivery_place: null,
    duration: null,
    venue: "Ankara Büyükşehir Belediyesi İhale Salonu",
    address: "Emniyet Mah. Hipodrom Caddesi No:5 Yenimahalle/Ankara",
    phone: "0312 507 30 01",
    detail_url: "https://www.ankara.bel.tr/ihaleler/detay/4086",
    doc_url: null,
    province: "Ankara",
    institution: "Ankara Büyükşehir Belediyesi",
    raw_data: {},
    first_seen_at: "2026-06-30T10:30:00+03:00",
    last_seen_at: "2026-07-16T09:15:00+03:00",
  },
  {
    id: 19,
    source: "istanbul",
    external_id: "2026/danismanlik-jeoloji",
    ikn: "2026/560213",
    title: "Jeoloji ve Jeofizik Etütleri Danışmanlık Hizmeti Alınacaktır",
    tender_type: "hizmet_alimi",
    procedure: "Belli İstekliler Arasında İhale Usulü",
    tender_datetime: "2026-09-10T10:00:00",
    unit: "Deprem ve Zemin İnceleme Müdürlüğü",
    status: null,
    description: "Mikrobölgeleme rapor ve haritalarının hazırlanması işi.",
    delivery_place: null,
    duration: null,
    venue: "İBB Bakırköy Ek Hizmet Binası İhale Salonu",
    address: "Osmaniye Mah. Çobançeşme Koşuyolu Bulvarı No:5 Bakırköy/İstanbul",
    phone: "0212 449 40 64",
    detail_url: "https://ibb.istanbul/ibb/ihaleler/ihale-ilanlari/danismanlik-jeoloji",
    doc_url: null,
    province: "İstanbul",
    institution: "İstanbul Büyükşehir Belediyesi",
    raw_data: {},
    first_seen_at: "2026-07-08T10:00:00+03:00",
    last_seen_at: "2026-07-16T09:15:00+03:00",
  },
  {
    id: 20,
    source: "kocaeli",
    external_id: "2026/1249534",
    ikn: "2026/1249534",
    title: "Uluslararası 16. Kocaeli Kitap Fuarı Organizasyonu Hizmeti Alınacaktır",
    tender_type: "hizmet_alimi",
    procedure: "Açık İhale Usulü",
    tender_datetime: "2026-08-11T14:00:00",
    unit: "Kültür Sanat ve Konservatuvar Şube Müdürlüğü",
    status: null,
    description: "Kitap fuarı organizasyon ve alan kurulum hizmeti.",
    delivery_place: null,
    duration: null,
    venue: "Kocaeli Büyükşehir Belediyesi İhale Salonu",
    address: "İzmit/Kocaeli",
    phone: "0262 318 20 00",
    detail_url: "https://www.kocaeli.bel.tr/haber/kitap-fuari-organizasyon-51528.html",
    doc_url: null,
    province: "Kocaeli",
    institution: "Kocaeli Büyükşehir Belediyesi",
    raw_data: {},
    first_seen_at: "2026-07-11T08:00:00+03:00",
    last_seen_at: "2026-07-16T09:15:00+03:00",
  },
  {
    id: 21,
    source: "istanbul",
    external_id: "2026/itfaiye-ayakkabi",
    ikn: "2026/224871",
    title: "4.279 Çift İtfaiye Yazlık İş Ayakkabısı Alımı",
    tender_type: "mal_alimi",
    procedure: "Açık İhale Usulü",
    tender_datetime: "2026-02-16T10:00:00",
    unit: "Levazım ve Ayniyat Şube Müdürlüğü",
    status: null,
    description: "İtfaiye personeli için yazlık iş ayakkabısı alımı.",
    delivery_place: "İstanbul İtfaiye Daire Başkanlığı",
    duration: "30 gün",
    venue: "İBB Bakırköy Ek Hizmet Binası İhale Salonu",
    address: "Osmaniye Mah. Çobançeşme Koşuyolu Bulvarı No:5 Bakırköy/İstanbul",
    phone: "0212 449 40 64",
    detail_url: "https://ibb.istanbul/ibb/ihaleler/ihale-ilanlari/itfaiye-ayakkabi",
    doc_url: null,
    province: "İstanbul",
    institution: "İstanbul Büyükşehir Belediyesi",
    raw_data: {},
    first_seen_at: "2026-01-10T09:00:00+03:00",
    last_seen_at: "2026-07-16T09:15:00+03:00",
  },
  {
    id: 22,
    source: "ankara",
    external_id: "2026/1310388",
    ikn: "2026/1310388",
    title: "Muhtelif Trafik Levha ve Malzemesi Alımı (3 Kısım)",
    tender_type: "mal_alimi",
    procedure: "Açık İhale Usulü",
    tender_datetime: "2026-08-10T10:30:00",
    unit: "Fen İşleri Dairesi Başkanlığı",
    status: null,
    description: "3 kısım muhtelif trafik levha ve malzeme alımı.",
    delivery_place: "Ankara ili sınırları içinde idarenin gösterdiği yerler",
    duration: "75 gün",
    venue: "Ankara Büyükşehir Belediyesi İhale Salonu",
    address: "Emniyet Mah. Hipodrom Caddesi No:5 Yenimahalle/Ankara",
    phone: "0212 449 42 60",
    detail_url: "https://www.ankara.bel.tr/ihaleler/detay/4059",
    doc_url: null,
    province: "Ankara",
    institution: "Ankara Büyükşehir Belediyesi",
    raw_data: {},
    first_seen_at: "2026-07-05T10:30:00+03:00",
    last_seen_at: "2026-07-16T09:15:00+03:00",
  },
  {
    id: 23,
    source: "kocaeli",
    external_id: "2026/et-nakil",
    ikn: "2026/449430",
    title: "Et Nakil Hizmeti Alınacaktır",
    tender_type: "hizmet_alimi",
    procedure: "Açık İhale Usulü",
    tender_datetime: "2026-04-15T10:00:00",
    unit: "Kombina Şube Müdürlüğü",
    status: null,
    description: "Kombinadan satış noktalarına et nakli hizmeti.",
    delivery_place: null,
    duration: "365 gün",
    venue: "Kocaeli Büyükşehir Belediyesi İhale Salonu",
    address: "İzmit/Kocaeli",
    phone: "0262 318 20 00",
    detail_url: "https://www.kocaeli.bel.tr/haber/et-nakil-hizmeti-49443.html",
    doc_url: null,
    province: "Kocaeli",
    institution: "Kocaeli Büyükşehir Belediyesi",
    raw_data: {},
    first_seen_at: "2026-03-01T08:00:00+03:00",
    last_seen_at: "2026-07-16T09:15:00+03:00",
  },
  {
    id: 24,
    source: "istanbul",
    external_id: "2026/asansor-yenileme",
    ikn: "2026/499912",
    title: "2026 Yılı Muhtelif Alanlarda Asansör Yenilenmesi Yapım İşi",
    tender_type: "yapim_isi",
    procedure: "Açık İhale Usulü",
    tender_datetime: "2026-04-28T10:00:00",
    unit: "Kent Estetiği Dairesi Başkanlığı",
    status: null,
    description: "Muhtelif alanlarda bulunan asansörlerin yenilenmesi işi.",
    delivery_place: null,
    duration: null,
    venue: "İBB Bakırköy Ek Hizmet Binası İhale Salonu",
    address: "Osmaniye Mah. Çobançeşme Koşuyolu Bulvarı No:5 Bakırköy/İstanbul",
    phone: "0212 449 40 64",
    detail_url: "https://ibb.istanbul/ibb/ihaleler/ihale-ilanlari/asansor-yenileme",
    doc_url: null,
    province: "İstanbul",
    institution: "İstanbul Büyükşehir Belediyesi",
    raw_data: {},
    first_seen_at: "2026-03-15T09:00:00+03:00",
    last_seen_at: "2026-07-16T09:15:00+03:00",
  },
  {
    id: 25,
    source: "ankara",
    external_id: "2026/bakim-onarim",
    ikn: "2026/667890",
    title: "Bakım ve Onarım Hizmeti Alınacaktır",
    tender_type: "hizmet_alimi",
    procedure: "Açık İhale Usulü",
    tender_datetime: "2026-03-05T10:00:00",
    unit: "Makine İkmal Bakım ve Onarım Dairesi Başkanlığı",
    status: null,
    description: "Araç ve iş makinelerinin bakım onarım hizmeti.",
    delivery_place: null,
    duration: "365 gün",
    venue: "Ankara Büyükşehir Belediyesi İhale Salonu",
    address: "Emniyet Mah. Hipodrom Caddesi No:5 Yenimahalle/Ankara",
    phone: "0312 507 30 01",
    detail_url: "https://www.ankara.bel.tr/ihaleler/detay/4049",
    doc_url: null,
    province: "Ankara",
    institution: "Ankara Büyükşehir Belediyesi",
    raw_data: {},
    first_seen_at: "2026-02-10T09:00:00+03:00",
    last_seen_at: "2026-07-16T09:15:00+03:00",
  },
];
